params: !!python/object:argparse.Namespace
  accelerator: gpu
  activation_dropout: 0.0
  attention_dropout: 0.0
  attention_mode: sliding_chunks
  attention_window: 512
  batch_size: 1
  beam_size: 4
  calibration_weights: null
  dev_jsons: null
  dev_source: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/dev.src
  dev_target: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/dev.trg.notag
  devices:
  - 0
  disable_checkpointing: false
  disable_validation_bar: true
  dropout: 0.0
  early_stopping_metric: vloss
  fp32: false
  from_pretrained: modified-mbart
  from_pretrained_decoder: MiriUll/german-gpt2_easy
  global_attention_indices:
  - -1
  grad_accum: 32
  grad_ckpt: true
  label_smoothing: 0.0
  lr: 0.0003
  lr_cooldown: 0
  lr_reduce_factor: 0.5
  lr_reduce_patience: 4
  max_epochs: 100
  max_input_len: 3072
  max_output_len: 1024
  max_steps: -1
  min_delta: 0.0005
  num_sanity_val_steps: 1
  num_workers: 24
  patience: 10
  pretrained_ckpt: null
  print_params: false
  progress_bar_refresh_rate: 10
  remove_special_tokens_containing: null
  remove_xml_in_json: false
  resume_ckpt: null
  save_dir: finetuned-mbart
  save_every_n_val_epochs: 0
  save_prefix: custom_decoder_dbmdz
  save_top_k: 5
  seed: 222
  src_lang: null
  src_tags_included: true
  test_jsons: null
  test_percent_check: 1.0
  test_source: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/test.src
  test_target: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/test.trg.notag
  tgt_lang: null
  tgt_tags_included: false
  tokenizer: modified-mbart
  train_jsons: null
  train_percent_check: 1.0
  train_source: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/train.src
  train_target: /home/joehms/repos/leichte-sprache-corpus/aligned/20min/train.trg.notag
  val_every: 1.0
  val_percent_check: 1.0
  wandb: null
  wandb_entity: null
